ANIMAL_CLASS_BASE:
  - "cat"
  - "dog"
  - "cow"
ANIMAL_CLASS_INCREMENTAL:
  - "horse"
  - "sheep"
INCREMENTAL_STEP: 1
MEMORY: 1000
MEMORY_TYPE: 'fix'
SAMPLING:
  STRATERGY: 'dpp'
  DISTANCE_METRIC: 'eucl'
  CLUSTER_SAMPLING: 'dist'
  CLUSTER_PROPORTION: 'prop'
  N_CLUSTERS: 5
DATASET:
  DATA_ROOT: '/media/gaurav/Incremental_pose/data/'
  IMAGES: '/media/gaurav/Incremental_pose/data/cropped_images/'
  AUG_IMAGES: '/media/gaurav/Incremental_pose/data/rotated_images_random_all_three/'
  ANNOT: '/media/gaurav/Incremental_pose/data/updated_df.csv'
  AUG_ANNOT: '/media/gaurav/Incremental_pose/data/updated_df_rotated_random_all_three.csv'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 512
  - 512
  HEATMAP_SIZE:
  - 128
  - 128
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 128
  - 128
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  BASE_DATA_FOR_INCREMENTAL: 0.1
  WORLD_SIZE: 4
  BATCH_SIZE: 20
  VAL_BATCH_SIZE: 20
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  OPTIMIZER: 'adam'
  LR: 0.0001
  WEIGHT_DECAY: 0
  LR_FACTOR: 0.1
  LR_STEP:
  - 15
  DPG_MILESTONE: 15
  DPG_STEP:
  - 19
TRAIN_INCREMENTAL:
  BASE_DATA_FOR_INCREMENTAL: 0.1
  AUGMENTATION: 'rotation'
  BATCH_SIZE: 10
  VAL_BATCH_SIZE: 10
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  KD_LOSS: False 
  OPTIMIZER: 'adam'
  LR: 0.0001
  WEIGHT_DECAY: 0
  LR_FACTOR: 0.1
  LR_STEP:
    - 15
  DPG_MILESTONE: 15
  DPG_STEP:
  - 19 