ANIMAL_CLASS: 'cat'
DATASET:
  IMAGES: '/media2/het/data/cropped_images/'
  ANNOT: '/media2/het/data/updated_df.csv'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 512
  - 512
  HEATMAP_SIZE:
  - 128
  - 128
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 1
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
  - 15
  DPG_MILESTONE: 10
  DPG_STEP:
  - 15
  - 19
