ANIMAL_CLASS_BASE:
  - "cat"
  - "dog"
  - "cow"
ANIMAL_CLASS_INCREMENTAL:
  - "horse"
  - "sheep"
INCREMENTAL_STEP: 1
MEMORY: 1000
MEMORY_TYPE: 'fix'
SAMPLING:
  STRATERGY: 'rbf-dpp'
  CLUSTER_SAMPLING: 'random'
  CLUSTER_PROPORTION: 'same'
  N_CLUSTERS: 0
  GAMMA: 100
DATASET:
  DATA_ROOT: '/media2/het/Incremental_pose/mnt/data/'
  IMAGES: '/media2/het/Incremental_pose/data/cropped_images/'
  AUG_IMAGES: '/media2/het/Incremental_pose/mnt/data/rotated_images/'
  ANNOT: '/media2/het/Incremental_pose/data/updated_df.csv'
  AUG_ANNOT: '/media2/het/Incremental_pose/mnt/data/updated_df_rotated_random_all_three.csv'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 512
  - 512
  HEATMAP_SIZE:
  - 128
  - 128
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: '/media2/het/Incremental_pose/animalpose/exp/96-oracle.yaml/model_Base.pth'
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 128
  - 128
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  BASE_DATA_FOR_INCREMENTAL: 0.1
  WORLD_SIZE: 4
  BATCH_SIZE: 13
  VAL_BATCH_SIZE: 13
  BEGIN_EPOCH: 0
  END_EPOCH: 0
  OPTIMIZER: 'adam'
  LR: 0.0001
  WEIGHT_DECAY: 0
  LR_FACTOR: 0.1
  LR_STEP:
  - 15
  - 25
  DPG_MILESTONE: 15
  DPG_STEP:
  - 19
  - 29
TRAIN_INCREMENTAL:
  BASE_DATA_FOR_INCREMENTAL: 0.1
  AUGMENTATION: 'rotation'
  BATCH_SIZE: 13
  VAL_BATCH_SIZE: 13
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  KD_LOSS: False 
  BALANCED_FINETUNING: False
  FINETUNING_NON_AUGMENTED: False
  FINETUNING_OLD_DATA: False
  FINETUNING_AUGMENTED: False
  ICARL: False
  EEIL: False
  OPTIMIZER: 'adam'
  LR: 0.0001
  WEIGHT_DECAY: 0
  LR_FACTOR: 0.1
  LR_STEP:
    - 15
  DPG_MILESTONE: 15
  DPG_STEP:
  - 19 