ANIMAL_CLASS_BASE:
  - "cat"
  - "dog"
  - "cow"
DATASET:
  DATA_ROOT: '/media2/het/Incremental_pose/data/'
  IMAGES: '/media2/het/Incremental_pose/data/cropped_images/'
  ANNOT: '/media2/het/Incremental_pose/data/updated_df.csv'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 512
  - 512
  HEATMAP_SIZE:
  - 128
  - 128
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 128
  - 128
  NUM_LAYERS: 50
C1: 
  TRAIN: True
  PRETRAINED: '/media2/het/AlphaPose/animalpose/exp/52-gaussian_model.yaml/final_weights.pth'
C2:
  TRAIN: True
  PRETRAINED: '/media2/het/AlphaPose/animalpose/exp/52-gaussian_model.yaml/final_weights_c2.pth'
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  BASE_DATA_FOR_INCREMENTAL: 0.1
  WORLD_SIZE: 4
  BATCH_SIZE: 2
  VAL_BATCH_SIZE: 10
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  OPTIMIZER: 'adam'
  LR: 0.00001
  WEIGHT_DECAY: 0
  LR_FACTOR: 0.1
  LR_STEP:
  - 15
  DPG_MILESTONE: 15
  DPG_STEP:
  - 19