ANIMAL_CLASS_BASE:
  - "cat"
  - "dog"
  - "cow"
ANIMAL_CLASS_INCREMENTAL:
  - "horse"
  - "sheep"
INCREMENTAL_STEP: 1
DATASET:
  IMAGES: '/media2/het/data/cropped_images/'
  ANNOT: '/media2/het/data/updated_df.csv'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 17
  IMAGE_SIZE:
  - 512
  - 512
  HEATMAP_SIZE:
  - 128
  - 128
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 128
  - 128
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  BASE_DATA_FOR_INCREMENTAL: 0
  WORLD_SIZE: 4
  BATCH_SIZE: 10
  VAL_BATCH_SIZE: 20
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
    - 15
    - 60
  DPG_MILESTONE: 19
  DPG_STEP:
    - 19
TRAIN_INCREMENTAL:
  BASE_DATA_FOR_INCREMENTAL: 0
  BATCH_SIZE: 10
  VAL_BATCH_SIZE: 20
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  KD_LOSS: False
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
    - 15
    - 60 
  DPG_MILESTONE: 19
  DPG_STEP:
    - 19 
    - 60